/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author LENOVO
 */
public class Menu_Utama extends javax.swing.JFrame {

    public Menu_Utama() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);//auto maxsize saat dirun
        
        mulai();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menusd = new javax.swing.JPanel();
        maincontent = new javax.swing.JPanel();
        utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        navbar.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        getContentPane().add(navbar, java.awt.BorderLayout.PAGE_START);

        sidebar.setBackground(new java.awt.Color(255, 255, 255));
        sidebar.setPreferredSize(new java.awt.Dimension(250, 475));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(0, 0));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(0, 0));

        menusd.setBackground(new java.awt.Color(255, 255, 255));
        menusd.setLayout(new javax.swing.BoxLayout(menusd, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(menusd);

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(sidebar, java.awt.BorderLayout.LINE_START);

        maincontent.setBackground(new java.awt.Color(255, 255, 255));

        utama.setBackground(new java.awt.Color(255, 255, 255));
        utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout maincontentLayout = new javax.swing.GroupLayout(maincontent);
        maincontent.setLayout(maincontentLayout);
        maincontentLayout.setHorizontalGroup(
            maincontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maincontentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        maincontentLayout.setVerticalGroup(
            maincontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(maincontent, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(596, 434));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Menu_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel maincontent;
    private javax.swing.JPanel menusd;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel utama;
    // End of variables declaration//GEN-END:variables

    private void mulai() {
        
       //sidebar submenu
       Menu_Item Barangmas1 = new Menu_Item(true, "Barang1",null);
       Menu_Item Barangmas2 = new Menu_Item(true, "Barang2",null);
       Menu_Item Barangmas3 = new Menu_Item(true, "Barang3",null);
       
       Menu_Item Transaksi1 = new Menu_Item(true, "Transaksi1",null);
       Menu_Item Transaksi2 = new Menu_Item(true, "Transaksi2",null);
       Menu_Item Transaksi3 = new Menu_Item(true, "Transaksi3",null);
        
       //sidebar
       Menu_Item menuMaster = new Menu_Item(false,  "Master",null, Barangmas1, Barangmas2, Barangmas3);
       Menu_Item menuTransaksi = new Menu_Item(false,  "Transaksi",null, Transaksi1, Transaksi2, Transaksi3);
       Menu_Item menuLaporan = new Menu_Item(false,  "Laporan",null);
       
       addMenu(menuMaster, menuTransaksi, menuLaporan);
    }
    
    private void addMenu(Menu_Item... menu){
        for(int i = 0; i <menu.length;i++){
        menusd.add(menu[i]);
        ArrayList<Menu_Item> subMenu = menu[i].getSubMenu();
        for(Menu_Item m : subMenu){
                addMenu(m);
            }
        }
        menusd.revalidate();
    }
}
